### ISSUE TITLE
There is a bug while the div gets pulled down within a tabular structure.

### ISSUE THREAD

**Issue by TandemNZ** [avokicchi/jquery-drawr#13]
I was trying to implement it but found this bug.
My HTML structure is tables based and DIVs have been nested within TDs.
Now say I am trying to implement this at 3rd row i.e 3rd TR.
First, 2 rows have already taken some height, assume some 400px!
So, this drawing tool starts from 400px, and there I found the issue.
I have managed to set the CANVAS, TOOLs everything, but once I tried drawing something, that didn't happen!
So, I started scratching the reason and I found the mouse events have been starting from 0,0 of the parent instead of 400,0. Or better to say, mouse events don't work at the 3rd TR or the CANVAS I had put inside.
Let me know if it's not clear!

**Comment by lieuweprins** [comment]
Was able to reproduce this pretty easily, thank you. I'll look into it

**Comment by TandemNZ** [comment]
Thanks. I am trying to search it but plz let me know the solution.

**Comment by lieuweprins** [comment]
It appears in the latest version, at least the drawing part of this problem has been resolved, now I just need to fix the positioning of the helper toolwindows.

**Comment by avokicchi** [comment]
drawr seems to work in tables now, it was due my use of offsetLeft which I made faulty assumptions about.
