### ISSUE TITLE
X and Y offsets are working differently when added in a modal

### ISSUE THREAD

**Issue by oividioscaeremos** [avokicchi/jquery-drawr#16]
Hey, I'm trying to use this app in a modal on my page but when I do it, it definitely goes crazy with where I'm clicking and where it's drawing. It is something that would match my expectations so if there's any solution that I can apply, I want to know. 

There are left and top parameters for many things in code but not every one of them works okay after I change their left-top value to `x-left` which `left` in that line is the left offset of my modal body. Pencil works fine now but it goes crazy when I try to use zoom.

Helpp please

**Comment by avokicchi** [comment]
Fixing #26 also seems to have fixed this. If not, feel free to open a new issue with an example
