### ISSUE TITLE
If we zoom out in mobile device and adjust image. Image will disappear from editor

### ISSUE THREAD

**Issue by Al-hamed-Mohammed** [avokicchi/jquery-drawr#26]
If we zoom out in mobile device and adjust image using mdi-cursor-move  Tool from tool bar.
 Image is disappear from editor.
Can any please help on this

**Comment by avokicchi** [comment]
This issue is reproducable on Desktop Google Chrome if you enable the device simulator, this should make debugging a lot easier. The issue is in drawSpot function of jquery.drawr.move.js. I'll look into it.

**Comment by avokicchi** [comment]
I have found the issue. It explains a ton of weird behaviour in the scrolling. I will publish an update later on. It was due to two typos in jquery.drawr.move.js.
